backend:
  name: github
  repo: faraazjabbar/decap-blog
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images

collections:
  - name: "blog"
    label: "Blog"
    folder: src/content/blog
    create: true
    format: frontmatter
    preview_path: blog/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: pubDate, label: Date, widget: date }
      - {
          label: "Publish",
          name: "isPublish",
          widget: "boolean",
          default: true,
        }
      - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
      - { name: body, label: Body, widget: markdown }
# title: 'First post'
# description: 'Lorem ipsum dolor sit amet'
# pubDate: 'Jul 08 2022'
# heroImage: '/blog-placeholder-3.jpg'
